name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required repository secrets
        run: |
          # Fail early with a clear message if required deploy secrets are missing
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" ] || [ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
            echo "ERROR: Required GitHub secrets FIREBASE_SERVICE_ACCOUNT_JSON and FIREBASE_PROJECT_ID are not set."
            echo "Please add them in your repository Settings → Secrets and Variables → Actions before enabling automatic deploys."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Prepare service account
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase-sa.json
          gcloud_auth() { echo; }

      - name: Install functions dependencies
        working-directory: bizcard_proxy/functions
        run: |
          npm install

      - name: Run functions unit tests
        working-directory: bizcard_proxy/functions
        run: |
          npm test

      - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-sa.json
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only functions --project "$FIREBASE_PROJECT"
